# Change prefix
set -g prefix2 M-\`
bind \` send-prefix -2

set -g extended-keys on                   # needed by Control + Shift bindings
set -s escape-time 10                     # faster command sequences
set -sg repeat-time 600                   # increase repeat timeout
set -s focus-events on

set -g history-limit 5000                 # boost history

# mouse support
set -g mouse on

# edit configuration
bind e run "vi ~/.config/tmux/tmux.conf"
# reload configuration
bind r run "tmux source ~/.config/tmux/tmux.conf" \; display "tmux config reloaded"

# -- display -------------------------------------------------------------------
set -g base-index 1           # start windows numbering at 1
setw -g pane-base-index 1     # make pane numbering consistent with windows

setw -g automatic-rename on   # rename window to reflect current program
set -g renumber-windows on    # renumber windows when a window is closed

set -g set-titles on          # set terminal title
set -g set-titles-string '#{pane_title}'

set -g display-panes-time 800 # slightly longer pane indicators display time
set -g display-time 1000      # slightly longer status messages display time

set -g status-interval 10     # redraw status line every 10 seconds

# clear both screen and history
bind -n C-l send-keys C-l \; run 'sleep 0.2' \; clear-history

# activity
set -g monitor-activity on
set -g visual-activity off

# -- navigation ----------------------------------------------------------------

# create session
bind C-c new-session

# find session
bind C-f command-prompt -p find-session 'switch-client -t %%'

# session navigation
bind BTab switch-client -l    # move to last session

# split pane
bind -n M-- split-window -v   # split current window horizontally
bind -n M-\\ split-window -h  # split current window vertically

# moving panes 
bind > swap-pane -D           # swap current pane with the next one
bind < swap-pane -U           # swap current pane with the previous one

# switching panes
bind -rn M-, select-pane -L   # move left
bind -rn M-. select-pane -R   # move right
bind -rn M-\< select-pane -D  # move down
bind -rn M-\> select-pane -U  # move up

# maximize current pane
bind -n M-z resize-pane -Z
# switch to previous pane without minimizing
bind -n M-q last-pane -Z

# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# window navigation
bind -rn S-Left previous-window  # select previous window
bind -rn S-Right next-window     # select next window
bind -n M-Tab last-window        # move to last active window

# moving windows
bind -r C-S-H swap-window -t -1 \; select-window -t -1  # swap current window with the previous one
bind -r C-S-L swap-window -t +1 \; select-window -t +1  # swap current window with the next one

# -- Plugins - tpm -----------------------------------------------------------------------
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_status_style "rounded"

# Initialize TMUX plugin manager
tmux set -g @catppuccin_window_text " #W"
tmux set -g @catppuccin_window_current_text " #W"
run '~/.config/tmux/plugins/tpm/tpm'

# Theme - catppuccin (Make the status line pretty and add some modules)
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

set -g @catppuccin_window_text "  #W "
set -g @catppuccin_window_current_text " * #W "
