# Prem - For p10k prompt

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:$PATH

# alias
source ~/.zsh.alias

# env vars
source ~/.zsh.env

# End Prem


### Added by Zinit's installer
if [[ ! -d $HOME/.zplug ]]; then
    print -P "%F{33} %F{220}Installing Plugin Manager (zplug/zplug)%f"
    command git clone https://github.com/zplug/zplug "$HOME/.zplug" && \
        print -P "%F{34}Installation successful.%f" || \
        print -P "%F{160}The clone has failed.%f"
fi
source "$HOME/.zplug/init.zsh"

# Install needed plugins
## powerlevel10k theme
zplug 'romkatv/powerlevel10k', as:theme, depth:1
## forgit
zplug 'wfxr/forgit'
## fzf-tab
zplug 'Aloxaf/fzf-tab'
## zsh syntax highlighting like fish
zplug "zsh-users/zsh-syntax-highlighting", defer:2
## autopair - auto-closes matching delimiters
zplug "hlissner/zsh-autopair", defer:2
## Additional completion definitions for Zsh
zplug "zsh-users/zsh-completions", defer:2
## Substring history
zplug "zsh-users/zsh-history-substring-search", defer:2
## zsh suggestions
zplug "zsh-users/zsh-autosuggestions", defer:2

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: \n"
    if read -q; then
        echo; zplug install
    fi

    #source plugins and add commands to $PATH
    zplug load --verbose
else
    #source plugins and add commands to $PATH
    zplug load
fi

# End of zplug

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

#ZSH_THEME="powerlevel10k/powerlevel10k"


plugins=(
  fzf
  #fzf-tab
  #autojump
  #zsh-syntax-highlighting
  #zsh-autopair
  #zsh-completions
  #zsh-history-substring-search
  #zsh-autosuggestions
  web-search
  copyfile
  git
  #globalias # to expand alias you type
  python
  sudo
  ssh-agent
  systemd
  systemadmin
  colored-man-pages
  history
)

source $ZSH/oh-my-zsh.sh

# User configuration
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Prem
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh" || true

## For globalias that expands alias you type
## Avoid expansion for basic commands
GLOBALIAS_FILTER_VALUES=(ls grep vi gco)

export COLUMNS="120"

# Prevent underlined text for filepath
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'
